ALTER TABLE daemons ADD COLUMN IF NOT EXISTS last_cache_stats JSONB;
ALTER TABLE daemons ADD COLUMN IF NOT EXISTS last_mem_stats JSONB;
ALTER TABLE daemons ADD COLUMN IF NOT EXISTS active_containers INTEGER NOT NULL DEFAULT 0;
